#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Generates a random isomorphic maze until it gets a termination signal
(Ctrl + C).
"""

from __future__ import absolute_import
from __future__ import print_function
from __future__ import unicode_literals

from random import choice
from argparse import ArgumentParser


def generate_maze():
    """
    Generates a random isomorphic maze in the stdout until it receives a
    keyboard interrupt.
    """
    try:
        while True:
            print(choice(['\\', '/']), end='')
    except KeyboardInterrupt:
        pass


if __name__ == '__main__':
    PARSER = ArgumentParser(description=__doc__)
    PARSER.add_argument('-v', '--version', action='version', version='1.0')
    PARSER.parse_args()

    generate_maze()
